"""renamed file to template and created file model

Revision ID: 66840441d089
Revises: 9442a80c75e5
Create Date: 2024-12-20 18:12:40.328251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66840441d089'
down_revision: Union[str, None] = '9442a80c75e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('file', sa.Column('template_id', sa.Integer(), nullable=False))
    op.drop_constraint('uix_filename_user', 'file', type_='unique')
    op.drop_constraint('file_tag_id_fkey', 'file', type_='foreignkey')
    op.drop_constraint('file_user_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'template', ['template_id'], ['id'])
    op.drop_column('file', 'vars')
    op.drop_column('file', 'user_id')
    op.drop_column('file', 'tag_id')
    op.drop_column('file', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('file', sa.Column('vars', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key('file_user_id_fkey', 'file', 'user', ['user_id'], ['id'])
    op.create_foreign_key('file_tag_id_fkey', 'file', 'tag', ['tag_id'], ['id'])
    op.create_unique_constraint('uix_filename_user', 'file', ['filename', 'user_id'])
    op.drop_column('file', 'template_id')
    op.drop_table('template')
    # ### end Alembic commands ###
