"""unique tag name and filename

Revision ID: 9442a80c75e5
Revises: 8cf1d507ee13
Create Date: 2024-12-20 15:26:04.842403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9442a80c75e5'
down_revision: Union[str, None] = '8cf1d507ee13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filename', sa.String(), nullable=False))
    op.create_unique_constraint('uix_filename_user', 'file', ['filename', 'user_id'])
    op.drop_column('file', 'name')
    op.create_unique_constraint('uix_name_user', 'tag', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_user', 'tag', type_='unique')
    op.add_column('file', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_filename_user', 'file', type_='unique')
    op.drop_column('file', 'filename')
    # ### end Alembic commands ###
